name: Build & Publish VSTO (main + testing to GitHub Pages)

permissions:
  contents: write  # nodig voor push naar gh-pages

on:
  push:
    branches:
      - main
      - testing
  workflow_dispatch: {}

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Restore NuGet
        run: nuget restore xafplugin.sln

      # --- Certificaat herstellen uit secrets ---
      - name: Restore signing certificate (PFX)
        id: cert
        shell: pwsh
        run: |
          if (-not "${{ secrets.CODESIGN_PFX_B64 }}") { throw "Missing secret CODESIGN_PFX_B64" }
          if (-not "${{ secrets.CODESIGN_PFX_PASSWORD }}") { throw "Missing secret CODESIGN_PFX_PASSWORD" }
          $bytes = [Convert]::FromBase64String("${{ secrets.CODESIGN_PFX_B64 }}")
          $pfxPath = Join-Path $env:RUNNER_TEMP "codesign.pfx"
          [IO.File]::WriteAllBytes($pfxPath, $bytes)
          "pfx_path=$pfxPath" | Out-File -FilePath $env:GITHUB_OUTPUT -Append

      - name: Determine branch and URLs
        id: meta
        shell: pwsh
        run: |
          $branch = "${{ github.ref_name }}"
          $base = "https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}"
          if ($branch -eq "testing") {
            $path = "clickonce-testing"
            $install = "$base/$path/"
            "publish_target=$path"        | Out-File -FilePath $env:GITHUB_OUTPUT -Append
            "install_url=$install"        | Out-File -FilePath $env:GITHUB_OUTPUT -Append
            "override_urls=true"          | Out-File -FilePath $env:GITHUB_OUTPUT -Append
          } elseif ($branch -eq "main") {
            $path = "clickonce"
            "publish_target=$path"        | Out-File -FilePath $env:GITHUB_OUTPUT -Append
            "override_urls=false"         | Out-File -FilePath $env:GITHUB_OUTPUT -Append
          } else {
            throw "Unexpected branch: $branch"
          }

      # Build + ClickOnce Publish (gesigned)
      # testing → override InstallUrl/UpdateUrl naar /clickonce-testing/
      - name: ClickOnce Publish (testing, signed)
        if: steps.meta.outputs.override_urls == 'true'
        shell: pwsh
        run: >
          msbuild xafplugin/xafplugin.csproj
          /t:Publish /p:Configuration=Release
          /p:AutoIncrementApplicationRevision=true
          /p:InstallUrl='${{ steps.meta.outputs.install_url }}'
          /p:UpdateUrl='${{ steps.meta.outputs.install_url }}'
          /p:SignManifests=true
          /p:ManifestKeyFile='${{ steps.cert.outputs.pfx_path }}'
          /p:ManifestKeyPassword='${{ secrets.CODESIGN_PFX_PASSWORD }}'

      # main → gebruik csproj (productie InstallUrl), geen URL-override
      - name: ClickOnce Publish (main, signed)
        if: steps.meta.outputs.override_urls != 'true'
        shell: pwsh
        run: >
          msbuild xafplugin/xafplugin.csproj
          /t:Publish /p:Configuration=Release
          /p:AutoIncrementApplicationRevision=true
          /p:SignManifests=true
          /p:ManifestKeyFile='${{ steps.cert.outputs.pfx_path }}'
          /p:ManifestKeyPassword='${{ secrets.CODESIGN_PFX_PASSWORD }}'

      # Maak een tijdelijke site-map met alléén de juiste subfolder
      - name: Prepare site folder for Pages
        shell: pwsh
        run: |
          if (Test-Path site) { Remove-Item -Recurse -Force site }
          New-Item -ItemType Directory -Force "site/${{ steps.meta.outputs.publish_target }}" | Out-Null
          Copy-Item "xafplugin\publish\*" "site\${{ steps.meta.outputs.publish_target }}" -Recurse -Force

      # Deploy naar gh-pages en bewaar bestaande files (zodat beide paden naast elkaar bestaan)
      - name: Deploy to gh-pages (keep existing files)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: site
          publish_branch: gh-pages
          keep_files: true
